/**
 * Tests for the static preview feature (--static flag).
 *
 * Run: node --test test/preview.test.js
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const { buildHtml, generateStaticPreview } = require('../lib/preview');
const { validateTranslations } = require('../lib/validate');
const { computeStats } = require('../lib/stats');

const FIXTURES = path.join(__dirname, 'fixtures');
const TMP = path.join(__dirname, '.tmp-preview');
const CLI = path.join(__dirname, '..', 'bin', 'po-csv-tool.js');

before(() => {
  fs.mkdirSync(TMP, { recursive: true });
});

after(() => {
  fs.rmSync(TMP, { recursive: true, force: true });
});

// ─── buildHtml — static mode flag ────────────────────────

describe('buildHtml — staticMode', () => {
  const rows = [
    { key: 'hello', translations: { en: 'Hello', pl: 'Cześć' } },
    { key: 'bye', translations: { en: 'Goodbye', pl: 'Do widzenia' } },
  ];
  const languages = ['en', 'pl'];
  const validationResult = { issues: [], refLang: 'en', totalKeys: 2 };
  const statsResult = {
    refLang: 'en',
    refKeyCount: 2,
    languages: ['en', 'pl'],
    langStats: [
      { lang: 'en', total: 2, translated: 2, missing: 0, coverage: 100, topMissing: [] },
      { lang: 'pl', total: 2, translated: 2, missing: 0, coverage: 100, topMissing: [] },
    ],
    overallCoverage: 100,
  };

  it('returns HTML string with STATIC_MODE = false by default', () => {
    const html = buildHtml(rows, languages, FIXTURES, validationResult, statsResult);
    assert.ok(html.includes('STATIC_MODE = false'), 'should contain STATIC_MODE = false');
  });

  it('returns HTML string with STATIC_MODE = true when staticMode=true', () => {
    const html = buildHtml(rows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(html.includes('STATIC_MODE = true'), 'should contain STATIC_MODE = true');
  });

  it('embeds all translation data in static mode', () => {
    const html = buildHtml(rows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(html.includes('Hello'), 'should contain English value');
    assert.ok(html.includes('Cześć'), 'should contain Polish value');
    assert.ok(html.includes('hello'), 'should contain key "hello"');
    assert.ok(html.includes('bye'), 'should contain key "bye"');
  });

  it('hides save bar in static mode', () => {
    const html = buildHtml(rows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(html.includes('id="saveBar"'), 'saveBar element should exist');
    // In static mode the save bar div should have display:none
    assert.ok(html.includes('style="display:none"'), 'save bar should be hidden with display:none');
  });

  it('includes static footer in static mode', () => {
    const html = buildHtml(rows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(
      html.includes('Static preview generated by'),
      'should contain static footer text'
    );
    assert.ok(
      html.includes('translation-toolkit'),
      'footer should mention translation-toolkit'
    );
  });

  it('does NOT include static footer in server mode', () => {
    const html = buildHtml(rows, languages, FIXTURES, validationResult, statsResult, false);
    assert.ok(
      !html.includes('Static preview generated by'),
      'server mode should NOT have static footer'
    );
  });

  it('includes client-side CSV parser in static mode', () => {
    const html = buildHtml(rows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(
      html.includes('parseCsvString') || html.includes('csvToData') || html.includes('clientDiff'),
      'should contain client-side diff functions'
    );
  });

  it('produces a valid HTML document', () => {
    const html = buildHtml(rows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(html.startsWith('<!DOCTYPE html>') || html.startsWith('<html'), 'should start with DOCTYPE or html tag');
    assert.ok(html.includes('</html>'), 'should end with closing html tag');
  });
});

// ─── generateStaticPreview ───────────────────────────────

describe('generateStaticPreview', () => {
  it('generates an HTML file from .po fixtures', async () => {
    const outPath = path.join(TMP, 'static-test.html');
    await generateStaticPreview(FIXTURES, outPath);

    assert.ok(fs.existsSync(outPath), 'output HTML file should exist');

    const content = fs.readFileSync(outPath, 'utf-8');
    assert.ok(content.includes('STATIC_MODE = true'), 'generated file should have STATIC_MODE = true');
    assert.ok(content.includes('simple.key'), 'should contain keys from fixture .po');
    assert.ok(content.includes('Simple value'), 'should contain values from en-US.po');
  });

  it('includes all languages from .po files', async () => {
    const outPath = path.join(TMP, 'langs-test.html');
    await generateStaticPreview(FIXTURES, outPath);

    const content = fs.readFileSync(outPath, 'utf-8');
    assert.ok(content.includes('en'), 'should include English');
    assert.ok(content.includes('pl'), 'should include Polish');
  });

  it('file size is reasonable (> 1 KB)', async () => {
    const outPath = path.join(TMP, 'size-test.html');
    await generateStaticPreview(FIXTURES, outPath);

    const stat = fs.statSync(outPath);
    assert.ok(stat.size > 1024, `file should be > 1 KB, got ${stat.size} bytes`);
  });
});

// ─── CLI: --static flag ──────────────────────────────────

describe('CLI --static flag', () => {
  it('generates default translation-preview/index.html', () => {
    const cwd = TMP;
    // Clean up any previous output
    const defaultDir = path.join(cwd, 'translation-preview');
    if (fs.existsSync(defaultDir)) fs.rmSync(defaultDir, { recursive: true });
    const defaultOutput = path.join(defaultDir, 'index.html');

    execFileSync(process.execPath, [CLI, 'preview', '--dir', FIXTURES, '--static'], {
      cwd,
      timeout: 10000,
    });

    assert.ok(fs.existsSync(defaultOutput), 'should create translation-preview/index.html');

    const content = fs.readFileSync(defaultOutput, 'utf-8');
    assert.ok(content.includes('STATIC_MODE = true'), 'default output should have STATIC_MODE = true');
  });

  it('respects -o / --output flag', () => {
    const customPath = path.join(TMP, 'custom-output.html');
    if (fs.existsSync(customPath)) fs.unlinkSync(customPath);

    execFileSync(process.execPath, [CLI, 'preview', '--dir', FIXTURES, '--static', '-o', customPath], {
      timeout: 10000,
    });

    assert.ok(fs.existsSync(customPath), 'should create file at custom output path');
  });

  it('uses short flags -s and -d', () => {
    const outPath = path.join(TMP, 'short-flags.html');
    if (fs.existsSync(outPath)) fs.unlinkSync(outPath);

    execFileSync(process.execPath, [CLI, 'preview', '-d', FIXTURES, '-s', '-o', outPath], {
      timeout: 10000,
    });

    assert.ok(fs.existsSync(outPath), 'should work with short flags -d -s -o');
  });

  it('rejects --watch + --static combination', () => {
    assert.throws(
      () => {
        execFileSync(process.execPath, [CLI, 'preview', '--dir', FIXTURES, '--static', '--watch'], {
          timeout: 10000,
          stdio: 'pipe',
        });
      },
      (err) => {
        return err.status !== 0;
      },
      'should exit with non-zero status when --watch and --static are combined'
    );
  });

  it('rejects --static when no .po files are found', () => {
    const emptyDir = path.join(TMP, 'empty-dir');
    fs.mkdirSync(emptyDir, { recursive: true });

    assert.throws(
      () => {
        execFileSync(process.execPath, [CLI, 'preview', '--dir', emptyDir, '--static'], {
          timeout: 10000,
          stdio: 'pipe',
        });
      },
      (err) => {
        return err.status !== 0;
      },
      'should exit with non-zero status when no .po files found'
    );
  });
});

// ─── Static HTML content validation ─────────────────────

describe('static HTML content', () => {
  let html;

  before(async () => {
    const outPath = path.join(TMP, 'content-test.html');
    await generateStaticPreview(FIXTURES, outPath);
    html = fs.readFileSync(outPath, 'utf-8');
  });

  it('contains all expected tabs', () => {
    assert.ok(html.includes('Translations'), 'should have Translations tab');
    assert.ok(html.includes('Validation'), 'should have Validation tab');
    assert.ok(html.includes('Statistics'), 'should have Statistics tab');
    assert.ok(html.includes('Diff'), 'should have Diff tab');
  });

  it('includes search input', () => {
    assert.ok(
      html.includes('id="search"') || html.includes('id="search-input"'),
      'should have a search input'
    );
  });

  it('includes inline editing guard for static mode', () => {
    assert.ok(
      html.includes('if (STATIC_MODE) return'),
      'should guard inline editing in static mode'
    );
  });

  it('does NOT contain server-dependent fetch calls as the only path', () => {
    // In static mode, the diff should use clientDiff, not just fetch('/api/diff')
    assert.ok(
      html.includes('clientDiff'),
      'should have clientDiff function for static diff computation'
    );
  });
});

// ─── buildHtml — plural rows ─────────────────────────────

describe('buildHtml — plural rows', () => {
  const pluralRows = [
    { key: 'hello', translations: { en: 'Hello', pl: 'Cześć' } },
    { key: '%d cat[0]', translations: { en: '%d cat', pl: '%d kot' }, isPlural: true, pluralForm: 0 },
    { key: '%d cat[1]', translations: { en: '%d cats', pl: '%d koty' }, isPlural: true, pluralForm: 1 },
    { key: '%d cat[2]', translations: { en: '', pl: '%d kotów' }, isPlural: true, pluralForm: 2 },
  ];
  const languages = ['en', 'pl'];
  const validationResult = { issues: [], refLang: 'en', totalKeys: 1, totalPluralKeys: 1 };
  const statsResult = {
    refLang: 'en',
    refKeyCount: 1,
    languages: ['en', 'pl'],
    langStats: [
      { lang: 'en', total: 1, translated: 1, missing: 0, coverage: 100, topMissing: [], pluralKeys: 1, pluralForms: 3, emptyPluralForms: 0 },
      { lang: 'pl', total: 1, translated: 1, missing: 0, coverage: 100, topMissing: [], pluralKeys: 1, pluralForms: 3, emptyPluralForms: 0 },
    ],
    overallCoverage: 100,
  };

  it('adds plural-row CSS class to plural entries', () => {
    const html = buildHtml(pluralRows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(html.includes('plural-row'), 'should have plural-row CSS class');
  });

  it('adds plural badge to plural rows', () => {
    const html = buildHtml(pluralRows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(html.includes('plural-badge'), 'should have plural-badge class');
    assert.ok(html.includes('plural'), 'should contain "plural" label text');
  });

  it('renders plural key with [N] suffix', () => {
    const html = buildHtml(pluralRows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(html.includes('%d cat[0]'), 'should render key with [0] suffix');
    assert.ok(html.includes('%d cat[1]'), 'should render key with [1] suffix');
    assert.ok(html.includes('%d cat[2]'), 'should render key with [2] suffix');
  });

  it('renders plural translations correctly', () => {
    const html = buildHtml(pluralRows, languages, FIXTURES, validationResult, statsResult, true);
    assert.ok(html.includes('%d kot'), 'should contain Polish singular');
    assert.ok(html.includes('%d koty'), 'should contain Polish form 1');
    assert.ok(html.includes('%d kotów'), 'should contain Polish form 2');
  });

  it('contains plural-row click guard in JavaScript', () => {
    const html = buildHtml(pluralRows, languages, FIXTURES, validationResult, statsResult, false);
    assert.ok(
      html.includes('plural-row') && html.includes('closest'),
      'should have plural-row click guard using closest()'
    );
  });
});

// ─── generateStaticPreview — plural content ──────────────

describe('generateStaticPreview — plural entries from fixtures', () => {
  let html;

  before(async () => {
    const outPath = path.join(TMP, 'plural-preview.html');
    await generateStaticPreview(FIXTURES, outPath);
    html = fs.readFileSync(outPath, 'utf-8');
  });

  it('includes plural rows from fixture .po files', () => {
    // Fixture has "%d files" plural entry → should appear as key[0], key[1]
    assert.ok(html.includes('[0]'), 'should have [0] plural form suffix');
    assert.ok(html.includes('[1]'), 'should have [1] plural form suffix');
  });

  it('includes plural-row CSS class in generated preview', () => {
    assert.ok(html.includes('plural-row'), 'should have plural-row CSS class');
  });

  it('includes plural-badge in generated preview', () => {
    assert.ok(html.includes('plural-badge'), 'should have plural-badge in generated HTML');
  });

  it('includes Polish plural forms from fixtures', () => {
    // pl-PL.po has "%d pliki" as a plural form
    assert.ok(html.includes('%d pliki') || html.includes('%d plik'), 'should contain Polish plural translations');
  });

  it('includes plural-row styling in CSS', () => {
    // The CSS should style tr.plural-row
    assert.ok(
      html.includes('tr.plural-row') || html.includes('.plural-row'),
      'CSS should style plural-row class'
    );
  });
});

// ─── Fuzzy badge in preview ──────────────────────────────

describe('generateStaticPreview — fuzzy badge', () => {
  let html;

  before(async () => {
    const outPath = path.join(TMP, 'fuzzy-preview.html');
    await generateStaticPreview(FIXTURES, outPath);
    html = fs.readFileSync(outPath, 'utf-8');
  });

  it('includes fuzzy-row CSS class in generated preview', () => {
    assert.ok(html.includes('fuzzy-row'), 'should have fuzzy-row CSS class');
  });

  it('includes fuzzy-badge in generated preview', () => {
    assert.ok(html.includes('fuzzy-badge'), 'should have fuzzy-badge in generated HTML');
  });

  it('marks fuzzy entries in DATA with isFuzzy flag', () => {
    assert.ok(html.includes('"isFuzzy":true'), 'DATA should contain isFuzzy:true for fuzzy entries');
  });

  it('includes fuzzy-row styling in CSS', () => {
    assert.ok(
      html.includes('tr.fuzzy-row') || html.includes('.fuzzy-row'),
      'CSS should style fuzzy-row class'
    );
  });
});
